### ISSUE TITLE
How can i use it with gulp 4? 

### ISSUE THREAD

**Issue by sedlukha** [juanfran/gulp-jade-inheritance#17]
setWatch task doesn't work with gulp 4

**Comment by pure180** [comment]
Gulp changes a lot with version 4.0.0, it's needed to rewrite the whole tasks. You will need to add the setwatch task as gulp.series( CB )... Take a look into the change log of new version.

**Comment by sedlukha** [comment]
I solved this problem by insert `global.isWatching = true;` into my jade task. So now we don't need `setWatch`task

thanks @pure180
